version: "3"
networks:
  mservices:
services:
  flask_app:
    build: ./flask_app
    volumes:
      - ./models:/flask_app/models
    environment:
      FLASK_ENV: product
    env_file: ../.env
    hostname: flask_app
    container_name: flask_app
    networks:
      mservices:
        aliases:
          - medicines-comparator
    ports:
      - "5000:5000"

  equivs_api:
    build: ./equivs_api
    volumes:
      - ./models:/equivs_api/models
    environment:
      FLASK_ENV: product
    env_file: ../.env
    hostname: equivs_api
    container_name: equivs_api
    networks:
      mservices:
        aliases:
          - medicines-comparator
    ports:
      - "5001:5001"

#networks:
#  mynetwork:
#    enable_ipv6: false
#    ipam:
#      config:
#        - subnet: 172.20.0.0/24