version: "3.9"
services:
  flask_app:
    build: ./flask_app
    restart: always
    volumes:
      - ./models:/flask_app/models
    environment:
      FLASK_ENV: development
    env_file: ../.env
    networks:
      mynetwork:
        ipv4_address: 172.20.0.2

  equivs_api:
    build: ./equivs_api
    restart: always
    volumes:
      - ./models:/equivs_api/models
    environment:
      FLASK_ENV: development
    env_file: ../.env
    networks:
      mynetwork:
        ipv4_address: 172.20.0.3

volumes:
  flask_app:
  equivs_api:

networks:
  mynetwork:
    enable_ipv6: false
    ipam:
      config:
        - subnet: 172.20.0.0/24